# setup timer
function timer:setup

# gamerules (generated by gamerules.py)
gamerule announceAdvancements false
gamerule commandBlockOutput false
gamerule disableElytraMovementCheck false
gamerule disableRaids true
gamerule doDaylightCycle false
gamerule doEntityDrops false
gamerule doFireTick false
gamerule doImmediateRespawn false
gamerule doInsomnia true
gamerule doLimitedCrafting false
gamerule doMobLoot true
gamerule doMobSpawning false
gamerule doPatrolSpawning true
gamerule doTileDrops false
gamerule doTraderSpawning false
gamerule doWeatherCycle false
gamerule drowningDamage true
gamerule fallDamage false
gamerule fireDamage false
gamerule forgiveDeadPlayers true
gamerule keepInventory true
gamerule logAdminCommands true
gamerule maxCommandChainLength 65536
gamerule maxEntityCramming 24
gamerule mobGriefing false
gamerule naturalRegeneration true
gamerule randomTickSpeed 3
gamerule reducedDebugInfo false
gamerule sendCommandFeedback true
gamerule showDeathMessages true
gamerule spawnRadius 0
gamerule spectatorsGenerateChunks true
gamerule universalAnger false

# other
recipe give @a *
defaultgamemode adventure
difficulty peaceful
weather clear
time set noon

# add team
team remove players
team add players
team modify players collisionRule never
team modify players friendlyFire false
team modify players seeFriendlyInvisibles true
team modify players deathMessageVisibility never
team modify players nametagVisibility never

# right click detection
scoreboard objectives remove used_warped
scoreboard objectives add used_warped minecraft.used:minecraft.warped_fungus_on_a_stick

# checkpoints
scoreboard objectives remove laps
scoreboard objectives add laps dummy
scoreboard objectives remove stage
scoreboard objectives add stage dummy

# final times
scoreboard objectives remove times
scoreboard objectives add times dummy

# ready check
scoreboard objectives remove ready
scoreboard objectives remove countdown
